version: 2.1

build-template: &build-template
  docker:
    - image: tarampampam/node:15-alpine
  steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: '.'
    - run:
        name: 'Build artifacts'
        command: |
          node --version
          npm --version
          yarn install
          yarn export 
    - persist_to_workspace:
        root: '.'
        paths:
          - '.'

upload-template: &upload-template
  docker:
    - image: bigbadalien/awscli-node-kops-kubectl:0.3
  steps:
    - setup_remote_docker
    - attach_workspace:
        at: '.'
    - run:
        name: 'Upload artifacts'
        command: |
          pwd
          echo "Uploading assets to $DOMAIN"
          aws s3 cp ./out s3://$DOMAIN/ --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600"
          echo "Invalidating CDN network"
          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' | jq -r '.Invalidation.Id'`
          echo "Invalidation ID is $INVALIDATION_ID"
          echo "CDN Invalidation request is sent."

jobs:
  # build
  build-stage:
    <<: *build-template
  build-prod:
    <<: *build-template
  # upload
  upload-stage:
    <<: *upload-template
  upload-prod:
    <<: *upload-template

workflows:
  version: 2.1
  clover_finance:
    jobs:
      # stage 
      - approve-stage:
          type: approval
      - build-stage:
          context: clover_build_stage
          requires:
            - approve-stage
      - upload-stage:
          context:
            - cicd
            - clover_build_stage
          requires:
            - build-stage
      # prod
      - approve-prod:
          type: approval
          filters:
            branches:
              only: [ master ]
      - build-prod:
          context: clover_build_prod
          requires:
            - approve-prod
      - upload-prod:
          context:
            - cicd
            - clover_build_prod
          requires:
            - build-prod

